[2021-04-21 20:17:33,756] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T13:30:00+00:00 [queued]>
[2021-04-21 20:17:33,788] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.sleep 2021-04-19T13:30:00+00:00 [queued]>
[2021-04-21 20:17:33,789] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:17:33,789] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-21 20:17:33,790] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:17:33,807] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): sleep> on 2021-04-19T13:30:00+00:00
[2021-04-21 20:17:33,815] {standard_task_runner.py:52} INFO - Started process 942 to run task
[2021-04-21 20:17:33,829] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'sleep', '2021-04-19T13:30:00+00:00', '--job-id', '379', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmp5g69nt9f', '--error-file', '/tmp/tmpcq2q8__q']
[2021-04-21 20:17:33,831] {standard_task_runner.py:77} INFO - Job 379: Subtask sleep
[2021-04-21 20:17:33,973] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.sleep 2021-04-19T13:30:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:17:34,092] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T13:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T13:30:00+00:00
[2021-04-21 20:17:34,094] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-21 20:17:34,097] {bash.py:158} INFO - Running command: sleep 5
[2021-04-21 20:17:34,130] {bash.py:169} INFO - Output:
[2021-04-21 20:17:39,140] {bash.py:177} INFO - Command exited with return code 0
[2021-04-21 20:17:39,173] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=sleep, execution_date=20210419T133000, start_date=20210421T201733, end_date=20210421T201739
[2021-04-21 20:17:39,199] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:17:39,214] {local_task_job.py:146} INFO - Task exited with return code 0
